alias brew='arch -arm64 brew'
alias cat='bat -p'
alias cd='z'
alias du='dust'
alias emc='emacsclient_background'
alias grep='rg'
alias ibrew='arch -x86_64 /usr/local/bin/brew'
alias ls='exa -aF'
alias lst='ls -sold'
alias rg='rg --color=auto --smart-case -uu'
alias rgf='rg --files | rg'
alias top='btm -b'
