edition = "2021"
fn_args_layout = "Vertical"
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "Vertical"
match_block_trailing_comma = true
max_width = 80
reorder_impl_items = true
struct_lit_single_line = false
unstable_features = true
